/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 logo-extrude.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo-extrude.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.009, -0.006, 0.015]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.157, -0.009, -0.157]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['SVGMat.003']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['SVGMat.004']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['SVGMat.005']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['SVGMat.006']} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials['SVGMat.007']} />
        <mesh geometry={nodes.Cylinder001_5.geometry} material={materials['SVGMat.008']} />
        <mesh geometry={nodes.Cylinder001_6.geometry} material={materials['SVGMat.009']} />
        <mesh geometry={nodes.Cylinder001_7.geometry} material={materials['SVGMat.010']} />
        <mesh geometry={nodes.Cylinder001_8.geometry} material={materials['SVGMat.011']} />
        <mesh geometry={nodes.Cylinder001_9.geometry} material={materials['SVGMat.012']} />
        <mesh geometry={nodes.Cylinder001_10.geometry} material={materials['SVGMat.013']} />
        <mesh geometry={nodes.Cylinder001_11.geometry} material={materials['SVGMat.014']} />
        <mesh geometry={nodes.Cylinder001_12.geometry} material={materials['SVGMat.015']} />
      </group>
    </group>
  )
}

useGLTF.preload('/logo-extrude.glb')
