/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 logo-mglb.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/logo-mglb.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Path_36003.geometry} material={materials['SVGMat.029']} />
      <mesh geometry={nodes.Path_36003_1.geometry} material={materials['SVGMat.017']} />
      <mesh geometry={nodes.Path_36003_2.geometry} material={materials['SVGMat.018']} />
      <mesh geometry={nodes.Path_36003_3.geometry} material={materials['SVGMat.019']} />
      <mesh geometry={nodes.Path_36003_4.geometry} material={materials['SVGMat.020']} />
      <mesh geometry={nodes.Path_36003_5.geometry} material={materials['SVGMat.021']} />
      <mesh geometry={nodes.Path_36003_6.geometry} material={materials['SVGMat.022']} />
      <mesh geometry={nodes.Path_36003_7.geometry} material={materials['SVGMat.023']} />
      <mesh geometry={nodes.Path_36003_8.geometry} material={materials['SVGMat.024']} />
      <mesh geometry={nodes.Path_36003_9.geometry} material={materials['SVGMat.025']} />
      <mesh geometry={nodes.Path_36003_10.geometry} material={materials['SVGMat.026']} />
      <mesh geometry={nodes.Path_36003_11.geometry} material={materials['SVGMat.027']} />
      <mesh geometry={nodes.Path_36003_12.geometry} material={materials['SVGMat.028']} />
    </group>
  )
}

useGLTF.preload('/logo-mglb.glb')
